### ISSUE TITLE
Circumstances when to Display Categories

### ISSUE THREAD

**Issue by talknshare** [pkp/browse#8]
For OPS 3.3.0.10, is there a way to hide to automatically hide the categories in the browse block if there are no preprints posted in that category? Also, how can we show the number of preprints posted in a category next to the category name in browse block? For example, "Biology (3)" where the category name only shows when there are at least 1 preprint posted in it, and in the parenthesis it will display the number of preprints. This will help the readers to not browse categories which have 0 items posted. It is an issue for us since we have around 10 categories to choose from for the submitting authors at the time of submission.

Thank you!

**Comment by asmecher** [comment]
@talknshare, this is more of a question than a bug; I'd suggest asking on our support forum (https://forum.pkp.sfu.ca). That's the best place to get help.
